version: "3"

services:
  backend:
    container_name: backend
    depends_on:
      - mysql
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - sleact
    ports:
      - "3095:3095"

  frontend:
    container_name: frontend
    depends_on:
      - backend
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - sleact
    volumes:
      - $PWD/frontend:/app/frontend
    ports:
      - "3090:3090"

  mysql:
    container_name: mysql
    restart: always
    # image: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    networks:
      - sleact
    # volumes:
    # - ./mysql:/etc/mysql/conf.d
    #   - mysql_vol1:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chanhyle

networks:
  sleact:
    driver: bridge
# volumes:
#   mysql_vol1:
#     driver_opts:
#       type: volume
#       o: "bind"
#       device: "/Users/chanhyle/Documents/data"
